version: '3.1'

services:

  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bpf54600jf
    ports:
      - "27017:27017"